language: java

jdk:
  - oraclejdk8

before_install:
  - chmod 755 -R ./travis # to deal with SVN possibly not holding permissions
  - ./travis/deps.sh # run linux or osx depending on environment

script:
  - cd build/
  - ant -Dmyenv=travis -f build.umple.xml first-build 
  # build against itself:
  - ant -Dmyenv=travis -f build.umple.xml build

  - ant -Dmyenv=travis # run all tests

os:
  - linux
  - osx
