language: java

jdk:
  - oraclejdk8

before_install:
  - chmod 755 -R ./travis # to deal with SVN possibly not holding permissions
  - ./travis/deps.sh # run linux or osx depending on environment

script:
  - cd build/
  - ant -Dmyenv=travis bootstrap
  - ant -Dmyenv=travis first-build
  # TODO https://github.com/umple/umple/issues/616
  # - ant -Dmyenv=travis build

os:
  - linux

  # Dropping osx for now, as oraclejdk8 does not appear to be available
  # /Users/travis/build.sh: line 41: jdk_switcher: command not found
  # - osx
