language: java

# jdk:
#   - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.ant/lib/
    - $TRAVIS_BUILD_DIR/dist/libs

before_install:
  - ./travis/deps.sh # run linux or osx depending on environment

script:
  - cd build/
  - ant -Dmyenv=travis bootstrap
  - ant -Dmyenv=travis first-build
  # TODO https://github.com/umple/umple/issues/616
  # - ant -Dmyenv=travis build

matrix:
  include:
    - os: linux
      language: java
      jdk: oraclejdk8
    - os: osx
      language: java