version: 1.26.0-{build}-{branch}

clone_depth: 5

cache:

- C:\Users\appveyor\.ant -> appveyor.yml
- C:\Users\appveyor\.ivy2 -> appveyor.yml
- C:\tools\php -> appveyor.yml
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml

init:

- cmd: gem update --system
- ps: cinst ant 2>&1 | Out-Null
# These next three are being installed separately as they are php dependents
# and were failing to install along with php
- ps: choco install kb3035131
- ps: choco install kb2919442
- os: choco install kb2999226
# install the latest php
- ps: choco install php

install:

- ps: $env:Path="C:\Ruby21\bin;C:/tools/ruby22/bin;C:\Program Files (x86)\Java\jdk1.8.0\bin;$($env:Path);C:\tools\php;C:\ProgramData\chocolatey\lib\ant"

- ps: ant -version
- ps: pushd build

- cmd: ant bootstrap
- cmd: ant deps-resolve-all

- ps: popd

- ps: php.exe --version
- ps: ruby.exe -v
- cmd: java.exe -version # using ps causes it to fail because it prints to sterr
- ps: ant -version
- ps: rake.bat -V

build_script:

- ps: cd build

- cmd: ant first-build
- cmd: ant -f build.umple.xml -Dfirst.build=false

test_script:

- cmd: ant -f build.testbed.xml -Dfirst.build=false

