version: 1.26.0-{build}-{branch}

skip_branch_with_pr: true

clone_depth: 5

platform:
  - x64

cache:

- C:\Users\appveyor\.ant -> appveyor.yml
- C:\Users\appveyor\.ivy2 -> appveyor.yml
- C:\tools\php -> appveyor.yml
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml

init:

#- cmd: gem update --system
#- ps: cinst ant 2>&1 | Out-Null  ## used to work
- ps: choco install ant --ignore-dependencies

# install some dependencies needed by php
- ps: choco install chocolatey-core.extension --ignore-dependencies

# install the latest php (dependencies kb2919442 kb3035131 kb2999226 were failing )
- ps: choco install php --ignore-dependencies

install:

- ps: $env:Path="C:\Ruby21\bin;C:/tools/ruby22/bin;C:\Program Files (x86)\Java\jdk1.8.0\bin;$($env:Path);C:\tools\php72;C:\tools\php;C:\ProgramData\chocolatey\lib\ant"

- ps: ant -version
- ps: pushd build

- cmd: ant bootstrap
- cmd: ant deps-resolve-all

- ps: popd

- cmd: php --version
- cmd: ruby -v
- cmd: java -version # using ps causes it to fail because it prints to sterr
- cmd: ant -version
- cmd: rake -V

build_script:

- ps: cd build

- cmd: ant first-build
- cmd: ant -f build.umple.xml -Dfirst.build=false -Dmyenv=appveyor

test_script:

- cmd: ant -f build.testbed.xml -Dfirst.build=false -Dmyenv=appveyor
- cmd: ant -f build.exampletests.xml allUserManualAndExampleTests -Dmyenv=appveyor

artifacts:

  path: dist
